from __future__ import absolute_import, division, print_function, unicode_literals

import os, sys

sys.path.append('python')

from beast.build import BuildState
from beast.build.Config import CONFIG

BuildState.run(sconstruct_globals=globals(), **CONFIG)
